language: node_js
dist: trusty

before_install:
  - curl -L https://releases.hashicorp.com/consul/1.0.1/consul_1.0.1_linux_amd64.zip -o /tmp/consul-bin.zip
  - unzip -o -d /tmp/bin /tmp/consul-bin.zip
  - /tmp/bin/consul --version
  - /tmp/bin/consul agent -server -dev &
  - sleep 5

node_js:
  - "8"
  - "9"
  - "node"

sudo: false
