language: node_js
dist: trusty
sudo: false

before_install:
  - curl -L https://releases.hashicorp.com/consul/0.7.2/consul_0.7.2_linux_amd64.zip -o /tmp/consul-bin.zip
  - unzip -o -d /tmp/bin /tmp/consul-bin.zip
  - /tmp/bin/consul --version
  - /tmp/bin/consul agent -server -dev &
  - sleep 5

node_js:
  - "4"
  - "6"
  - "7"
  - "node"
