language: node_js
dist: trusty

env:
  - CONSUL=0.9.3
  - CONSUL=1.4.0

before_install:
  - curl -L "https://releases.hashicorp.com/consul/${CONSUL}/consul_${CONSUL}_linux_amd64.zip" -o /tmp/consul-bin.zip
  - unzip -o -d /tmp/bin /tmp/consul-bin.zip
  - /tmp/bin/consul --version
  - /tmp/bin/consul agent -server -dev &
  - sleep 5

node_js:
  - "8"
  - "9"
  - "node"

sudo: false
